image: openjdk:11

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper

pipelines:
  default:
    - step:
        name: Build
        size: 2x
        caches:
          - gradle
          - gradlewrapper
          - node
        script:
          - bash ./gradlew --build-cache --no-daemon -i -S publish -PbuildVersion=CI
    - step:
        name: Deploy to Test
        deployment: test
        trigger: manual
        size: 2x
        caches:
          - gradle
          - gradlewrapper
          - node
        script:
          - bash ./gradlew --build-cache --no-daemon -i -S prepareTestDeploy -PdeployVersion=CURRENT -PbuildVersion=CI
          - scp ./build/test-content/* ec2-user@test.standalone.mgh.jumpco.io:/var/www/html/request-tracker-ui/
  custom:
    perform-release:
      - step:
          name: Perform Release
          size: 2x
          caches:
            - gradle
            - gradlewrapper
            - node
          script:
            - bash ./scripts/check-release.sh
            - git checkout master
            - git config --global user.email "$email"
            - git config --global user.name "$SCM_USERNAME"
            - git remote set-url origin https://bitbucket.org/tsctech/ethics1st-web-content.git
            - bash ./gradlew -S clean currentVersion -Prelease.pushTagsOnly -PprodBuild -PbuildVersion=CI
            - git tag
            - bash ./gradlew -S -i release -Prelease.pushTagsOnly -Prelease.disableChecks -Prelease.attachRemote=$SCM_URL -PprodBuild -PbuildVersion=CI
            - bash ./gradlew -S -i publish -Prelease.pushTagsOnly -PbuildVersion=CI
            - git tag
            - bash ./gradlew -S currentVersion  -Prelease.forceSnapshot -PbuildVersion=CI -PprodBuild
            - git tag
    deploy-release-test:
      - step:
          name: Deploy Last Release to Test
          deployment: test
          size: 2x
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew -i -S prepareTestDeploy -PdeployVersion=RELEASE -PbuildVersion=CI
            - scp ./build/test-content/* ec2-user@test.standalone.mgh.jumpco.io:/var/www/html/request-tracker-ui/
    deploy-latest-test:
      - step:
          name: Deploy Latest Snapshot to Test
          deployment: test
          size: 2x
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew -i -S prepareTestDeploy -PdeployVersion=LATEST -PbuildVersion=CI
            - scp ./build/test-content/* ec2-user@test.standalone.mgh.jumpco.io:/var/www/html/request-tracker-ui/
    deploy-current-test:
      - step:
          name: Deploy Current Build to Test
          deployment: test
          size: 2x
          caches:
            - gradle
            - gradlewrapper
            - node
          script:
            - bash ./gradlew -i -S testDeploy -PdeployVersion=CURRENT -PbuildVersion=CI
            - scp ./build/test-content/* ec2-user@test.standalone.mgh.jumpco.io:/var/www/html/request-tracker-ui/
#    deploy-release-prod:
#      - step:
#          deployment: production
#          caches:
#            - gradle
#            - gradlewrapper
#          script:
#            - bash ./gradlew -i -S productionDeploy -PdeployVersion=RELEASE -PbuildVersion=CI
