export enum APP_ROUTES {
  LOGOUT = 'logout',
  HOME = 'home',
  LOGIN = 'login',
  REGISTER = 'register',
  COMPLETE_REGISTER = 'complete-register',
  RESET_PASSWORD = 'reset-password',
  PROFILE = 'profile',
  CASES_TABLES = 'cases-table',
  CASE_DETAIL = 'case-detail',
  USER_MANAGEMENT = 'user-management',
  SCHEME_OFFICIALS = 'scheme-officials',
  DIVISIONS = 'divisions',
  SCHEMES = 'schemes',
  SERVICE_PROVIDER_NETWORKS = 'service-provider-networks',
  OPERATIONS_DEPARTMENT = 'operations-departments',
  FUND_MANAGEMENT_DEPARTMENT = 'fund-management-departments',
}
